name: My Test Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 23f2002758@ds.study.iitm.ac.in
        run: echo "Hello, world!"
